import { ArrowUpDown, Search } from "lucide-react";
import { Link } from "react-router-dom";
import { useMemo, useState } from "react";
import type { Queue, QueueStatus } from "../../types/api";
import { formatDate, formatPercentage, formatWait, locationLabel } from "../../utils/format";
import { StatusBadge } from "../common/StatusBadge";
import { EmptyState } from "../common/AsyncState";

const statuses: Array<"ALL" | QueueStatus> = ["ALL", "NORMAL", "BUSY", "CROWDED", "CRITICAL", "CLOSED"];

export function QueueTable({ queues }: { queues: Queue[] }) {
  const [term, setTerm] = useState(""); const [filter, setFilter] = useState<(typeof statuses)[number]>("ALL"); const [ascending, setAscending] = useState(true);
  const shown = useMemo(() => queues.filter((queue) => (filter === "ALL" || queue.status === filter) && queue.name.toLowerCase().includes(term.toLowerCase())).sort((a, b) => ascending ? a.name.localeCompare(b.name) : b.name.localeCompare(a.name)), [queues, term, filter, ascending]);
  if (!queues.length) return <EmptyState label="No queues found." />;
  return <section className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between"><label className="relative block"><span className="sr-only">Search queues</span><Search className="absolute left-3 top-2.5 text-slate-400" size={17} /><input value={term} onChange={(event) => setTerm(event.target.value)} placeholder="Search queues" className="w-full rounded-md border border-slate-300 py-2 pl-9 pr-3 text-sm sm:w-64" /></label><label className="text-sm font-medium text-slate-600">Status <select value={filter} onChange={(event) => setFilter(event.target.value as typeof filter)} className="ml-2 rounded-md border border-slate-300 p-2">{statuses.map((status) => <option key={status}>{status}</option>)}</select></label></div><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3"><button className="inline-flex items-center gap-1" onClick={() => setAscending(!ascending)}>Queue <ArrowUpDown size={13} /></button></th><th className="px-4 py-3">Location</th><th className="px-4 py-3">People</th><th className="px-4 py-3">Capacity</th><th className="px-4 py-3">Density</th><th className="px-4 py-3">Estimated wait</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Last updated</th></tr></thead><tbody className="divide-y divide-slate-100">{shown.map((queue) => <tr key={queue.id} className="hover:bg-slate-50"><td className="px-4 py-3 font-semibold text-blue-700"><Link to={`/queues/${queue.id}`} className="focus:outline-none focus:underline">{queue.name}</Link></td><td className="px-4 py-3">{locationLabel(queue.location_id)}</td><td className="px-4 py-3">{queue.current_count}</td><td className="px-4 py-3">{queue.capacity}</td><td className="px-4 py-3">{formatPercentage(queue.density)}</td><td className="px-4 py-3">{formatWait(queue.estimated_wait_time)}</td><td className="px-4 py-3"><StatusBadge status={queue.status} /></td><td className="px-4 py-3 text-slate-500">{formatDate(queue.updated_at)}</td></tr>)}</tbody></table></div>{!shown.length && <div className="p-6 text-center text-slate-500">No queues match the current filters.</div>}</section>;
}
